### PR TITLE
don't mix up int and size_t (first pass to fix that)

### PR DESCRIPTION
**Pull request by jeromelebel**
There is a problem with 64bits system

### CODE REVIEW

**Comment by jeromelebel** [comment]
Here there is still a problem with buffer over using 64bits. but I have more diff to send if you accept that one.

**Comment by gjmurakami-10gen** [comment]
These changes primarily seem to be changing size_t to int? The use of
size_t for lengths is a standard practice.

What problem are you seeing?

On Mon, Jan 7, 2013 at 4:33 PM, Jérôme Lebel notifications@github.comwrote:

> ## There is a problem with 64bits system
> 
> You can merge this Pull Request by running
> 
>   git pull https://github.com/fotonauts/mongo-c-driver size_t_64_bits
> 
> Or view, comment on, or merge it at:
> 
>   https://github.com/mongodb/mongo-c-driver/pull/63
> Commit Summary
> - don't mix up int and size_t (first pass to fix that)
> 
> File Changes
> - _M_ src/bcon.c (2)
> - _M_ src/bson.c (59)
> - _M_ src/bson.h (20)
> - _M_ src/encoding.c (10)
> - _M_ src/encoding.h (4)
> - _M_ src/env.c (24)
> - _M_ src/env.h (4)
> - _M_ src/gridfs.c (20)
> - _M_ src/gridfs.h (4)
> - _M_ src/mongo.c (24)
> 
> Patch Links:
> - https://github.com/mongodb/mongo-c-driver/pull/63.patch
> - https://github.com/mongodb/mongo-c-driver/pull/63.diff

## 

*
{\* name     : "_Gary J. Murakami, Ph.D._",
  title    : "Lead Engineer and Ruby Evangelist",
  company  : "10gen (the MongoDB company)",
  location : "New York, NY",
  email    : "gary.murakami@10gen.com",
  mobile   : "1-908-787-6621",
  im       : "gjmurakami (AIM)",
  twitter  : "@GaryMurakami",
  blog     : "grayghostwriter.blogspot.com",
  website  : "www.nobell.org",
  linkedin : "www.linkedin.com/pub/gary-murakami/1/36a/327" _}_

**Comment by gjmurakami-10gen** [comment]
Whoop, let me review again - moving to size_t (not away) is good.

On Mon, Jan 7, 2013 at 4:46 PM, Gary Murakami gary.murakami@10gen.comwrote:

> These changes primarily seem to be changing size_t to int? The use of
> size_t for lengths is a standard practice.
> 
> What problem are you seeing?
> 
> On Mon, Jan 7, 2013 at 4:33 PM, Jérôme Lebel notifications@github.comwrote:
> 
> > ## There is a problem with 64bits system
> > 
> > You can merge this Pull Request by running
> > 
> >   git pull https://github.com/fotonauts/mongo-c-driver size_t_64_bits
> > 
> > Or view, comment on, or merge it at:
> > 
> >   https://github.com/mongodb/mongo-c-driver/pull/63
> > Commit Summary
> > - don't mix up int and size_t (first pass to fix that)
> > 
> > File Changes
> > - _M_ src/bcon.c (2)
> > - _M_ src/bson.c (59)
> > - _M_ src/bson.h (20)
> > - _M_ src/encoding.c (10)
> > - _M_ src/encoding.h (4)
> > - _M_ src/env.c (24)
> > - _M_ src/env.h (4)
> > - _M_ src/gridfs.c (20)
> > - _M_ src/gridfs.h (4)
> > - _M_ src/mongo.c (24)
> > 
> > Patch Links:
> > - https://github.com/mongodb/mongo-c-driver/pull/63.patch
> > - https://github.com/mongodb/mongo-c-driver/pull/63.diff
> 
> ## 
> 
> *
> {\* name     : "_Gary J. Murakami, Ph.D._",
>   title    : "Lead Engineer and Ruby Evangelist",
>   company  : "10gen (the MongoDB company)",
>   location : "New York, NY",
>   email    : "gary.murakami@10gen.com",
>   mobile   : "1-908-787-6621",
>   im       : "gjmurakami (AIM)",
>   twitter  : "@GaryMurakami",
>   blog     : "grayghostwriter.blogspot.com",
>   website  : "www.nobell.org",
>   linkedin : "www.linkedin.com/pub/gary-murakami/1/36a/327" _}_

## 

*
{\* name     : "_Gary J. Murakami, Ph.D._",
  title    : "Lead Engineer and Ruby Evangelist",
  company  : "10gen (the MongoDB company)",
  location : "New York, NY",
  email    : "gary.murakami@10gen.com",
  mobile   : "1-908-787-6621",
  im       : "gjmurakami (AIM)",
  twitter  : "@GaryMurakami",
  blog     : "grayghostwriter.blogspot.com",
  website  : "www.nobell.org",
  linkedin : "www.linkedin.com/pub/gary-murakami/1/36a/327" _}_

**Comment by gjmurakami-10gen** [comment]
OK, I definitely want to pickup your size_t fixes.  But I have to first
push out the 0.7.1 release so that the slight interface changes will show
up on with 0.8.

Thanks again.

On Mon, Jan 7, 2013 at 4:49 PM, Gary Murakami gary.murakami@10gen.comwrote:

> Whoop, let me review again - moving to size_t (not away) is good.
> 
> On Mon, Jan 7, 2013 at 4:46 PM, Gary Murakami gary.murakami@10gen.comwrote:
> 
> > These changes primarily seem to be changing size_t to int? The use of
> > size_t for lengths is a standard practice.
> > 
> > What problem are you seeing?
> > 
> > On Mon, Jan 7, 2013 at 4:33 PM, Jérôme Lebel notifications@github.comwrote:
> > 
> > > ## There is a problem with 64bits system
> > > 
> > > You can merge this Pull Request by running
> > > 
> > >   git pull https://github.com/fotonauts/mongo-c-driver size_t_64_bits
> > > 
> > > Or view, comment on, or merge it at:
> > > 
> > >   https://github.com/mongodb/mongo-c-driver/pull/63
> > > Commit Summary
> > > - don't mix up int and size_t (first pass to fix that)
> > > 
> > > File Changes
> > > - _M_ src/bcon.c (2)
> > > - _M_ src/bson.c (59)
> > > - _M_ src/bson.h (20)
> > > - _M_ src/encoding.c (10)
> > > - _M_ src/encoding.h (4)
> > > - _M_ src/env.c (24)
> > > - _M_ src/env.h (4)
> > > - _M_ src/gridfs.c (20)
> > > - _M_ src/gridfs.h (4)
> > > - _M_ src/mongo.c (24)
> > > 
> > > Patch Links:
> > > - https://github.com/mongodb/mongo-c-driver/pull/63.patch
> > > - https://github.com/mongodb/mongo-c-driver/pull/63.diff
> > 
> > ## 
> > 
> > *
> > {\* name     : "_Gary J. Murakami, Ph.D._",
> >   title    : "Lead Engineer and Ruby Evangelist",
> >   company  : "10gen (the MongoDB company)",
> >   location : "New York, NY",
> >   email    : "gary.murakami@10gen.com",
> >   mobile   : "1-908-787-6621",
> >   im       : "gjmurakami (AIM)",
> >   twitter  : "@GaryMurakami",
> >   blog     : "grayghostwriter.blogspot.com",
> >   website  : "www.nobell.org",
> >   linkedin : "www.linkedin.com/pub/gary-murakami/1/36a/327" _}_
> 
> ## 
> 
> *
> {\* name     : "_Gary J. Murakami, Ph.D._",
>   title    : "Lead Engineer and Ruby Evangelist",
>   company  : "10gen (the MongoDB company)",
>   location : "New York, NY",
>   email    : "gary.murakami@10gen.com",
>   mobile   : "1-908-787-6621",
>   im       : "gjmurakami (AIM)",
>   twitter  : "@GaryMurakami",
>   blog     : "grayghostwriter.blogspot.com",
>   website  : "www.nobell.org",
>   linkedin : "www.linkedin.com/pub/gary-murakami/1/36a/327" _}_

## 

*
{\* name     : "_Gary J. Murakami, Ph.D._",
  title    : "Lead Engineer and Ruby Evangelist",
  company  : "10gen (the MongoDB company)",
  location : "New York, NY",
  email    : "gary.murakami@10gen.com",
  mobile   : "1-908-787-6621",
  im       : "gjmurakami (AIM)",
  twitter  : "@GaryMurakami",
  blog     : "grayghostwriter.blogspot.com",
  website  : "www.nobell.org",
  linkedin : "www.linkedin.com/pub/gary-murakami/1/36a/327" _}_

**Comment by gjmurakami-10gen** [comment]
tracking in CDRIVER-188 Use size_t to follow standard practice (slight API change)

**Pull request merged**
