### PR TITLE
1. Warnings removed from mongo.c. 2. problem with conn_->primary->host not initialized properly implemented. 3. Added full support to compile properly with Visual Studio in 64bits. 4. Added support to integrate chunk compression/encryption on GridFS. 5. A

### PR DESCRIPTION
**Pull request by jsbattig**
This commit contained removal of several warnings on Mongo.c under Visual Studio 2010 and also solves the problem of conn_->primary->host not properly initialized the right way.
The current code as reported on Jira, doesn't solve the problem because doesn't check the state of the first character of the string but rather the value of the pointer
Other main thing done is to add proper support for 64 bits compilations. There were specific variables that should have been declared to hold 64 bits values (like socket handle) and many explicit casts were needed

### CODE REVIEW

**Comment by gjmurakami-10gen** [comment]
Could you partition this pull request into cohesive component and individual pull requests?  The simpler pull requests are more likely to be merged, allowing us to converge somewhat.

**Comment by jsbattig** [comment]
Thanks for your response!
I apologize by the accumulation of requests and my in-expertise with GIT, I
think this was the first project where I use GIT seriously.

About splitting the requests, I will see what I can do.
In essence I can summarize them in three buckets, and you tell me what you
are interested on...:
1. Miscellaneous stability/cleanness changes when working on Visual Studio
   targeting Windows platforms.
2. Large enhancements to the client side to GridFS in order to:
   a. Improve overall performance
   b. Support chunk/random reading and writing
   c. Add support for "filtering" every individual chunk on the way in and
   out to add features such as Compression or Encryption.
   d. Doing some cleanup of the code for readability sake (splitting on
   smaller procedures, etc...)
3. Finally, I introduced code to simplify debugging of rogue programmers
   using the client wrong by adding validation of Mongo client objects on
   every public API function. The trick is very simple, adding a magic number
   to every mongo object and checking for it every time an object is going to
   be used. It's relatively low weight check and makes it for very safe
   operation rather than having to debug nasty access violations with memory
   corruptions in the middle.

Best regards and thanks for reaching out about the pull request. Honestly,
I was thinking it was going to be ditched so I just kept pulling the
mainstream code and merging into the codebase we are using at the company I
work for.

Seba

**Comment by gjmurakami-10gen** [comment]
No problem, we're thankful for people who are willing to contribute, and we
want to be great members of the community.

Using the numbering and list from the pull request, how about starting with
(1) Warnings removed from mongo.c
(2) problem with conn_->primary->host not initialized properly implemented
(3) Added full support to compile properly with Visual Studio in 64bits
I'm still somewhere in the middle of 64bit Windows VM dev env setup, but
want to get to (3) ASAP.

Thanks for your patience, and I hope that you can bear with us.  I'm
juggling a lot - lead engineer at the NY office (guiding 7 other driver
engineers), responsibilities with mongo-ruby-driver, mongo-meta-driver,
mongo-c-driver, mongo-performance, consulting with mongo-orchestration,
plus interviewing, support, customer consulting, sales support,
teaching/training, etc.

-Gary

On Mon, Jan 7, 2013 at 3:22 PM, jsbattig notifications@github.com wrote:

> Thanks for your response!
> I apologize by the accumulation of requests and my in-expertise with GIT,
> I
> think this was the first project where I use GIT seriously.
> 
> About splitting the requests, I will see what I can do.
> In essence I can summarize them in three buckets, and you tell me what you
> are interested on...:
> 1. Miscellaneous stability/cleanness changes when working on Visual Studio
>    targeting Windows platforms.
> 2. Large enhancements to the client side to GridFS in order to:
>    a. Improve overall performance
>    b. Support chunk/random reading and writing
>    c. Add support for "filtering" every individual chunk on the way in and
>    out to add features such as Compression or Encryption.
>    d. Doing some cleanup of the code for readability sake (splitting on
>    smaller procedures, etc...)
> 3. Finally, I introduced code to simplify debugging of rogue programmers
>    using the client wrong by adding validation of Mongo client objects on
>    every public API function. The trick is very simple, adding a magic number
>    to every mongo object and checking for it every time an object is going to
>    be used. It's relatively low weight check and makes it for very safe
>    operation rather than having to debug nasty access violations with memory
>    corruptions in the middle.
> 
> Best regards and thanks for reaching out about the pull request. Honestly,
> I was thinking it was going to be ditched so I just kept pulling the
> mainstream code and merging into the codebase we are using at the company
> I
> work for.
> 
> Seba
> 
> On Mon, Jan 7, 2013 at 2:01 PM, gjmurakami-10gen
> notifications@github.comwrote:
> 
> > Could you partition this pull request into cohesive component and
> > individual pull requests? The simpler pull requests are more likely to
> > be
> > merged, allowing us to converge somewhat.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/mongodb/mongo-c-driver/pull/47#issuecomment-11968661>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mongodb/mongo-c-driver/pull/47#issuecomment-11969593.

## 

*
{\* name     : "_Gary J. Murakami, Ph.D._",
  title    : "Lead Engineer and Ruby Evangelist",
  company  : "10gen (the MongoDB company)",
  location : "New York, NY",
  email    : "gary.murakami@10gen.com",
  mobile   : "1-908-787-6621",
  im       : "gjmurakami (AIM)",
  twitter  : "@GaryMurakami",
  blog     : "grayghostwriter.blogspot.com",
  website  : "www.nobell.org",
  linkedin : "www.linkedin.com/pub/gary-murakami/1/36a/327" _}_

**Comment by jsbattig** [comment]
Gary, I think  you will have to send a support request to GitHub so they
get rid of my composite pull request:
See this:
https://groups.google.com/forum/?fromgroups=#!topic/github/L0HaEprp7Fs

Then I have to figure out how to do the more atomic pull requests. Maybe by
creating orphan branches or something like that... Do you have any
suggestion?

Sebastian

**Comment by gjmurakami-10gen** [comment]
Sebastian:

I can just close the composite pull request from this side.

Perhaps you can do a fresh fork of mongo-c-driver master, and apply change
set, make pull request, and iterate?

On Tue, Jan 8, 2013 at 2:45 PM, jsbattig notifications@github.com wrote:

> Gary, I think you will have to send a support request to GitHub so they
> get rid of my composite pull request:
> See this:
> https://groups.google.com/forum/?fromgroups=#!topic/github/L0HaEprp7Fs
> 
> Then I have to figure out how to do the more atomic pull requests. Maybe
> by
> creating orphan branches or something like that... Do you have any
> suggestion?
> 
> Sebastian
> 
> On Mon, Jan 7, 2013 at 3:08 PM, gjmurakami-10gen
> notifications@github.comwrote:
> 
> > No problem, we're thankful for people who are willing to contribute, and
> > we
> > want to be great members of the community.
> > 
> > Using the numbering and list from the pull request, how about starting
> > with
> > (1) Warnings removed from mongo.c
> > (2) problem with conn_->primary->host not initialized properly
> > implemented
> > (3) Added full support to compile properly with Visual Studio in 64bits
> > I'm still somewhere in the middle of 64bit Windows VM dev env setup, but
> > want to get to (3) ASAP.
> > 
> > Thanks for your patience, and I hope that you can bear with us. I'm
> > juggling a lot - lead engineer at the NY office (guiding 7 other driver
> > engineers), responsibilities with mongo-ruby-driver, mongo-meta-driver,
> > mongo-c-driver, mongo-performance, consulting with mongo-orchestration,
> > plus interviewing, support, customer consulting, sales support,
> > teaching/training, etc.
> > 
> > -Gary
> > 
> > On Mon, Jan 7, 2013 at 3:22 PM, jsbattig notifications@github.com
> > wrote:
> > 
> > > Thanks for your response!
> > > I apologize by the accumulation of requests and my in-expertise with
> > > GIT,
> > > I
> > > think this was the first project where I use GIT seriously.
> > > 
> > > About splitting the requests, I will see what I can do.
> > > In essence I can summarize them in three buckets, and you tell me what
> > > you
> > > are interested on...:
> > > 1. Miscellaneous stability/cleanness changes when working on Visual
> > >    Studio
> > >    targeting Windows platforms.
> > > 2. Large enhancements to the client side to GridFS in order to:
> > >    a. Improve overall performance
> > >    b. Support chunk/random reading and writing
> > >    c. Add support for "filtering" every individual chunk on the way in
> > >    and
> > >    out to add features such as Compression or Encryption.
> > >    d. Doing some cleanup of the code for readability sake (splitting on
> > >    smaller procedures, etc...)
> > > 3. Finally, I introduced code to simplify debugging of rogue
> > >    programmers
> > >    using the client wrong by adding validation of Mongo client objects on
> > >    every public API function. The trick is very simple, adding a magic
> > >    number
> > >    to every mongo object and checking for it every time an object is
> > >    going
> > >    to
> > >    be used. It's relatively low weight check and makes it for very safe
> > >    operation rather than having to debug nasty access violations with
> > >    memory
> > >    corruptions in the middle.
> > > 
> > > Best regards and thanks for reaching out about the pull request.
> > > Honestly,
> > > I was thinking it was going to be ditched so I just kept pulling the
> > > mainstream code and merging into the codebase we are using at the
> > > company
> > > I
> > > work for.
> > > 
> > > Seba
> > > 
> > > On Mon, Jan 7, 2013 at 2:01 PM, gjmurakami-10gen
> > > notifications@github.comwrote:
> > > 
> > > > Could you partition this pull request into cohesive component and
> > > > individual pull requests? The simpler pull requests are more likely
> > > > to
> > > > be
> > > > merged, allowing us to converge somewhat.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > > 
> > > https://github.com/mongodb/mongo-c-driver/pull/47#issuecomment-11968661>.
> > > 
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/mongodb/mongo-c-driver/pull/47#issuecomment-11969593>.
> > 
> > ## 
> > 
> > *
> > {\* name : "_Gary J. Murakami, Ph.D._",
> > title : "Lead Engineer and Ruby Evangelist",
> > company : "10gen (the MongoDB company)",
> > location : "New York, NY",
> > email : "gary.murakami@10gen.com",
> > mobile : "1-908-787-6621",
> > im : "gjmurakami (AIM)",
> > twitter : "@GaryMurakami",
> > blog : "grayghostwriter.blogspot.com",
> > website : "www.nobell.org",
> > linkedin : "www.linkedin.com/pub/gary-murakami/1/36a/327" _}_
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/mongodb/mongo-c-driver/pull/47#issuecomment-11971750>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mongodb/mongo-c-driver/pull/47#issuecomment-12013720.

## 

_{_ name     : "_Gary J. Murakami, Ph.D._",
  title    : "Lead Engineer and Ruby Evangelist",
  company  : "10gen (the MongoDB company)",
  location : "New York, NY",
  email    : "gary.murakami@10gen.com",
  mobile   : "1-908-787-6621",
  im       : "gjmurakami (AIM)",
  twitter  : "@GaryMurakami",
  blog     : "grayghostwriter.blogspot.com",
  website  : "www.nobell.org",
  linkedin : "www.linkedin.com/pub/gary-murakami/1/36a/327" _}_

**Comment by gjmurakami-10gen** [comment]
--> iterate using the same fork

On Tue, Jan 8, 2013 at 3:58 PM, Gary Murakami gary.murakami@10gen.comwrote:

> Sebastian:
> 
> I can just close the composite pull request from this side.
> 
> Perhaps you can do a fresh fork of mongo-c-driver master, and apply change
> set, make pull request, and iterate?
> 
> On Tue, Jan 8, 2013 at 2:45 PM, jsbattig notifications@github.com wrote:
> 
> > Gary, I think you will have to send a support request to GitHub so they
> > get rid of my composite pull request:
> > See this:
> > https://groups.google.com/forum/?fromgroups=#!topic/github/L0HaEprp7Fs
> > 
> > Then I have to figure out how to do the more atomic pull requests. Maybe
> > by
> > creating orphan branches or something like that... Do you have any
> > suggestion?
> > 
> > Sebastian
> > 
> > On Mon, Jan 7, 2013 at 3:08 PM, gjmurakami-10gen
> > notifications@github.comwrote:
> > 
> > > No problem, we're thankful for people who are willing to contribute,
> > > and
> > > we
> > > want to be great members of the community.
> > > 
> > > Using the numbering and list from the pull request, how about starting
> > > with
> > > (1) Warnings removed from mongo.c
> > > (2) problem with conn_->primary->host not initialized properly
> > > implemented
> > > (3) Added full support to compile properly with Visual Studio in 64bits
> > > I'm still somewhere in the middle of 64bit Windows VM dev env setup,
> > > but
> > > want to get to (3) ASAP.
> > > 
> > > Thanks for your patience, and I hope that you can bear with us. I'm
> > > juggling a lot - lead engineer at the NY office (guiding 7 other driver
> > > engineers), responsibilities with mongo-ruby-driver, mongo-meta-driver,
> > > mongo-c-driver, mongo-performance, consulting with mongo-orchestration,
> > > plus interviewing, support, customer consulting, sales support,
> > > teaching/training, etc.
> > > 
> > > -Gary
> > > 
> > > On Mon, Jan 7, 2013 at 3:22 PM, jsbattig notifications@github.com
> > > wrote:
> > > 
> > > > Thanks for your response!
> > > > I apologize by the accumulation of requests and my in-expertise with
> > > > GIT,
> > > > I
> > > > think this was the first project where I use GIT seriously.
> > > > 
> > > > About splitting the requests, I will see what I can do.
> > > > In essence I can summarize them in three buckets, and you tell me
> > > > what
> > > > you
> > > > are interested on...:
> > > > 1. Miscellaneous stability/cleanness changes when working on Visual
> > > >    Studio
> > > >    targeting Windows platforms.
> > > > 2. Large enhancements to the client side to GridFS in order to:
> > > >    a. Improve overall performance
> > > >    b. Support chunk/random reading and writing
> > > >    c. Add support for "filtering" every individual chunk on the way in
> > > >    and
> > > >    out to add features such as Compression or Encryption.
> > > >    d. Doing some cleanup of the code for readability sake (splitting on
> > > >    smaller procedures, etc...)
> > > > 3. Finally, I introduced code to simplify debugging of rogue
> > > >    programmers
> > > >    using the client wrong by adding validation of Mongo client objects
> > > >    on
> > > >    every public API function. The trick is very simple, adding a magic
> > > >    number
> > > >    to every mongo object and checking for it every time an object is
> > > >    going
> > > >    to
> > > >    be used. It's relatively low weight check and makes it for very safe
> > > >    operation rather than having to debug nasty access violations with
> > > >    memory
> > > >    corruptions in the middle.
> > > > 
> > > > Best regards and thanks for reaching out about the pull request.
> > > > Honestly,
> > > > I was thinking it was going to be ditched so I just kept pulling the
> > > > mainstream code and merging into the codebase we are using at the
> > > > company
> > > > I
> > > > work for.
> > > > 
> > > > Seba
> > > > 
> > > > On Mon, Jan 7, 2013 at 2:01 PM, gjmurakami-10gen
> > > > notifications@github.comwrote:
> > > > 
> > > > > Could you partition this pull request into cohesive component and
> > > > > individual pull requests? The simpler pull requests are more likely
> > > > > to
> > > > > be
> > > > > merged, allowing us to converge somewhat.
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub<
> > > > 
> > > > https://github.com/mongodb/mongo-c-driver/pull/47#issuecomment-11968661>.
> > > > 
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > > > https://github.com/mongodb/mongo-c-driver/pull/47#issuecomment-11969593>.
> > > 
> > > ## 
> > > 
> > > *
> > > {\* name : "_Gary J. Murakami, Ph.D._",
> > > title : "Lead Engineer and Ruby Evangelist",
> > > company : "10gen (the MongoDB company)",
> > > location : "New York, NY",
> > > email : "gary.murakami@10gen.com",
> > > mobile : "1-908-787-6621",
> > > im : "gjmurakami (AIM)",
> > > twitter : "@GaryMurakami",
> > > blog : "grayghostwriter.blogspot.com",
> > > website : "www.nobell.org",
> > > linkedin : "www.linkedin.com/pub/gary-murakami/1/36a/327" _}_
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/mongodb/mongo-c-driver/pull/47#issuecomment-11971750>.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/mongodb/mongo-c-driver/pull/47#issuecomment-12013720.
> 
> ## 
> 
> _{_ name     : "_Gary J. Murakami, Ph.D._",
> 
>   title    : "Lead Engineer and Ruby Evangelist",
>   company  : "10gen (the MongoDB company)",
>   location : "New York, NY",
>   email    : "gary.murakami@10gen.com",
>   mobile   : "1-908-787-6621",
>   im       : "gjmurakami (AIM)",
>   twitter  : "@GaryMurakami",
>   blog     : "grayghostwriter.blogspot.com",
>   website  : "www.nobell.org",
>   linkedin : "www.linkedin.com/pub/gary-murakami/1/36a/327" _}_

## 

_{_ name     : "_Gary J. Murakami, Ph.D._",
  title    : "Lead Engineer and Ruby Evangelist",
  company  : "10gen (the MongoDB company)",
  location : "New York, NY",
  email    : "gary.murakami@10gen.com",
  mobile   : "1-908-787-6621",
  im       : "gjmurakami (AIM)",
  twitter  : "@GaryMurakami",
  blog     : "grayghostwriter.blogspot.com",
  website  : "www.nobell.org",
  linkedin : "www.linkedin.com/pub/gary-murakami/1/36a/327" _}_

**Comment by gjmurakami-10gen** [comment]
Closing, as we are working together to make individual small pull requests.

**Pull request closed without merging**
