### PR TITLE
Feature scons install target

### PR DESCRIPTION
**Pull request by ChrisLundquist**
- Someone else broke your build with net.h and net.c on master
- Adds scons install
- Adds scons uninstall

This lets installing my write_mongodb plugin for collectd to work without being a configuration nightmare.

There is probably a better way, but I just learned scons 30 minutes ago.

### CODE REVIEW

**Comment by ChrisLundquist** [comment]
@banker anything I can do here to help see this through?

**Comment by banker** [comment]
Sorry for the late reply. I'll try to pull this in in the next few days.

**Comment by ChrisLundquist** [comment]
Sounds good! Thank you. If there is anything that I should shore up, let me know.

**Comment by banker** [comment]
Just committed your install targets for SCons. Got rid of platform.h, so don't need that one anymore.

**Comment by ChrisLundquist** [comment]
Thank you! This will make https://github.com/octo/collectd happy!

**Comment by banker** [comment]
Awesome -- thanks for the contribution!

**Pull request closed without merging**
