### PR TITLE
Remove unused bson_buffer_size(.) and add helper bson_position(.)

### PR DESCRIPTION
**Pull request by paulmelnikow**

### CODE REVIEW

**Comment by gjmurakami-10gen** [comment]
Thanks for the contribution.  Github says that "This pull request cannot be automatically merged" so I'll look into merging it manually.

**Comment by gerald-lindsly** [comment]
Functions published in the header usually _are_ used almost by definition.  bson_buffer_size() is used by all 3 of the drivers: rmongodb, MongoMatlabDriver and MongoDelphiDriver.  I feel it is a useful function so that users can monitor how big their finished objects will be.  Perhaps bson_buffer_size() could be written in terms of mongo_bson_position() and make that private (static).

**Comment by gjmurakami-10gen** [comment]
Gerald:

Thanks for chiming in about bson_buffer_size(), I'll make sure that it
remains, and look into making mongo_bson_position() private.

On Sat, Mar 16, 2013 at 2:23 PM, Gerald Lindsly notifications@github.comwrote:

> Functions published in the header usually _are_ used almost by
> definition. bson_buffer_size() is used by all 3 of the drivers: rmongodb,
> MongoMatlabDriver and MongoDelphiDriver. I feel it is a useful function so
> that users can tell how big their finished objects will be. Perhaps
> bson_buffer_size() could be written in terms of mongo_bson_position() and
> make that private (static).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mongodb/mongo-c-driver/pull/79#issuecomment-15009653
> .

## 

_{_ name     : "_Gary J. Murakami, Ph.D._",
  title    : "Lead Engineer and Ruby Evangelist",
  company  : "10gen (the MongoDB company)",
  location : "New York, NY",
  email    : "gary.murakami@10gen.com",
  mobile   : "1-908-787-6621",
  im       : "gjmurakami (AIM)",
  twitter  : "@GaryMurakami",
  blog     : "grayghostwriter.blogspot.com",
  website  : "www.nobell.org",
  linkedin : "www.linkedin.com/pub/gary-murakami/1/36a/327" _}_

**Comment by paulmelnikow** [comment]
Thanks both for the feedback. I'll post a new pull request with the changes.

**Comment by paulmelnikow** [comment]
Let me know what you think!

**Pull request closed without merging**
