### PR TITLE
Refactored to remove duplication on function that sends messages to mongo

### PR DESCRIPTION
**Pull request by jsbattig**
There was a long standing ToDo on mongo CRUD operations to send msg and check for writeconcern. Code added to remove duplication

### CODE REVIEW

**Comment by gerald-lindsly** [comment]
Diff blew up.  Can't tell what you did.

**Comment by jsbattig** [comment]
Yeah. I'm checking. I think something with CR/LF

**Comment by jsbattig** [comment]
Something going on with git. I replayed the changes on mongo master branch fresh code and re-commited. Still sending diff crazy

**Comment by jsbattig** [comment]
Do people use core.autocrlf on GIT for this repo?

**Comment by jsbattig** [comment]
Close this pull request and use the new one. This one had messed up cr/lf

**Pull request closed without merging**
