### PR TITLE
nicer init_bson

### PR DESCRIPTION
**Pull request by jeromelebel**
nicer init_bson

### CODE REVIEW

**Comment by jsbattig** [comment]
I have macros for all statically initialized objects besides bsons... I didn't send a pull request for the rest (this one came as part of GridFS enhancements) because it was a little controversial at first. :)

Maybe I should send a pull request with the other statically initialized objects with macros like this one.

The only thing with a fully initialized object as you recommend on this pull request is that all members of the object have values so I imagine the generated code will be slightly less efficient. I got some arguments against "over initializing" objects as an efficiency concern. I come from Object Pascal world, where "new" style objects (since 1995 or so...) are always completely zero initialized making easy to write destructors with no concern that member pointers will have garbage. 
My tendency will be to support your changes to maintain the INIT_XXXX macros in a way all members of the struct are zero initialized.

It will be interesting to see how many cycles this consumes on the generated code, but I assume new compilers will probably use some of the new instruction set that leverage movement of large amount of data with few cycles...

**Comment by gjmurakami-10gen** [comment]
While the current C driver leaves a lot of room for performance improvement, performance is still one of the big goals.  I understand the desire for improved debugging, but I'm not in favor of adding (more) unnecessary initialization unless it can be turned off (or at least reduced to a minimum) like assert or DEBUG macros, and is probably off by default.  Sebastian, thanks for commenting.  Anyone else care to chime in?

**Comment by gerald-lindsly** [comment]
We pretty much covered this turf a week or so ago.  No unnecessary initialization because almost always we call a some form of _init () function.  In those rare cases where there is static initialization of a bson struct, a macro with just a few parameters might be nicer than manually initializing the members with a struct literal.

**Comment by jeromelebel** [comment]
This is not about performance or debugging. This is just obvious (at least for me). The diff for src/bson.h is about consistency. It's too weird for me to initialize half of a struct. I don't even understand there is no error or warning about it.
For the rest, since INIT_BSON, it's nicer to use it.

Please merge this request, or close it (well, all my requests, in fact). I mean I will not close a request unless I have something better to suggest.

**Comment by gerald-lindsly** [comment]
It's not initializing 'half a struct'.  This is just a shorthand notation.  All fields not mentioned are zeroed.   Even still... #define BSON_INIT { NULL, NULL }  is not so good in MSVS 10.  I examined the generated code.  Extra code is emitted to specifically set the mentioned fields and then the rest of the struct is zeroed with memset.  If you insist on zeroing the structure before calling an init function on it anyway then a call to memset produces better code and this can be generalized to #define ZERO(s) memset((void*)&s, 0, sizeof(s))

**Comment by jeromelebel** [comment]
I don't insist, I just suggest. Ok, I didn't know about the rest being zeroed. I guess, { NULL, NULL } should be replaced by {}.

**Comment by gerald-lindsly** [comment]
Unfortunately, {} is a syntax error.  Declare your struct variable without an initializer and put ZERO(variable) first thing.  Of course, need to define ZERO().   Perhaps should rename this to MONGO_ZERO() to avoid a name clash.

**Comment by jsbattig** [comment]
or the other thing we can do is refactor all places where there was explicit initialization of struct ( with the macro I put together or with literal ) and replace code explicit calls to init functions....

Any thoughts?

**Pull request closed without merging**
