### PR TITLE
Multiple enhancements to gridfs

### PR DESCRIPTION
**Pull request by jsbattig**
This commit contains many enhancements to gridfs, particularly:
1. Support for random writing
2. Buffering for better performance (read and write)
3. Support for pre and post processing of chunks, allows for easy plugin of compression and/or encryption
4. Ability to disable md5 calculation
5. Overall refactoring for clarity
6. Small modification on how to use gridfile_writer_init. The user before using this method must use to properly initialize the structure.

### CODE REVIEW

**Comment by chergert** [comment]
Can you break these up into a bunch of smaller commits? For example, the BSON changes should be in their own commit. I have a bunch of comments on the various sections, but it would be better if they were split first.

**Comment by jsbattig** [comment]
Can you try to merge the GridFS specific changes? I already tried to split the changes in multiple pull requests. I think I only left on bson file a macro for memory protection changes (makes debugging very easy). You don't have to use this feature or merge it into the target code, but if you do other pull requests I created further integrate this functionality.
This pull request really has most of the enhancements I put together overall, mostly enhancing GridFS to have full support of the typical functions you need from a full blown data streaming system.

**Comment by paulmelnikow** [comment]
These look like a bunch of good changes, but I'm wondering if the GridFS changes can be incorporated without the addition of the memory protection scheme, which has a wider ranging impact. The bson.c change, gitignore changes, and two commits (which remove and replace files?) seem to confuse this too.

It doesn't look like you've added tests which test and demonstrate the added functionality. Would you put some together?

**Comment by jsbattig** [comment]
Paul, thanks for the reply.  

The GridFS changes can be incorporated without the addition of the memory protection, no problem with that.

The protection check on every function call is done with a macro and it can be disabled by not #define(ing) a specific macro.

Now, I do recommend this protection checks to be incorporated eventually (again, they are active with a #define, but the performance minded can deactivate them when sure the application behaves properly). I found cases where even slight mishap on understanding expectation of objects lifecycle leads to attempts destroying the same object twice, and things like that.  
Actually, I have seen lately merges of code that addressed issues such as this, but for C code which tends to be packaged up on libraries and used from other languages, it comes pretty handy to learn to use the client liberally knowing any misunderstanding on the objects lifecycle is going to be caught.

Now, about the tests, my bad I didn't write them on C. I was doing full lifecycle development from C to Delphi, so I write all comprehensive tests on DUnit to build this, but I can certainly write some tests on C to show the functionality. I was a matter of just working more comfortably with DUnit framework which makes it easy to run all tests, or select individual tests and provides good feedback… again, y bad, there might be a good way to run the tests on C with assertions as they are currently designed obtaining good feedback.
The times I run them from Visual Studio, when there was an assertion the app will just exit, and I didn't spend too much time researching if there was some other way to run them that provides feedback on the failing test with some call stack dump or something like that…

It will take me a few weeks to get back to this tough… hope you are fine waiting.  

## 

José Sebastián Battig
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by jsbattig** [comment]
Added several tests to grids_test.c. I had to adjust a couple of tests with a new requirement to call grid file_init BEFORE calling gridfile_writer_init.
Tests show also example of single call to set file size that result in either truncation or expansion of file

**Comment by jsbattig** [comment]
Also, I'll appreciate if you can merge the changes centered around GridFS ignoring the mongo protection if you don't want to include them I do recommend them, in the near future after the pull requests I submitted are incorporated I will submit more pull requests that will incorporate again the full version of the memory protection scheme which is used for all mongo objects on the fork I created of mongo client.

**Comment by chergert** [comment]
The term memory protection is a bit misleading. I'm unconvinced on its value.

**Comment by jsbattig** [comment]
I agree. The term "memory protection" is not descriptive of what this does. 
The functionality allows to learn the client in a "safe" way where programmer mistakes managing lifecycle of objects or even Mongo bugs are caught by this code, as no function call is allowed if the object in question is not "alive".
This is really a debugging tool, you don't need to active it for production code.
You will notice it's composed of three parts:
1. Initialization of a "magic" number on the startup of the struct that holds the object.
2. A macro that when active will check the value of this magic number on all mongo c driver objects.
3. a Finalization mechanism than when disposing/destroying  objects will set this magic number to 0 before freeing memory

If the developer by error, or even if Mongo itself due to some bug decides to call a function on a "dead" object, a bson_fatal error will be raised. With this mechanism, I found some issues on how mongo c driver was managing objects lifecycle, and found my own issues. One of them was address on a pull request I saw recently regarding empty_bson lifecycle. Still, I found this very useful during the development cycle as these type of errors are common with c programs and when developers are learning a new framework.

I'm open to suggestion on a better name for this feature given the description I have provided above.

Regards

Sebastian

**Comment by paulmelnikow** [comment]
I'm hoping some of my recent work will make memory management a lot easier to handle, but can see value in a feature like this. I don't like that it needs support throughout the core driver, instead of just in destroy, for example.

What I'd rather see is a function that programmers can place around the various struct \* parameters when they make calls to the driver. If it's clean enough to incorporate  into most or all of the test cases, it should detect bugs in the driver, too.

As far as the name, how about "zombie check"?

**Comment by jeromelebel** [comment]
the zombie check should be handled by malloc, so by the system. That's annoying to have deal with a zombie check for each libraries.

**Comment by jsbattig** [comment]
jerome, you are correct, it's annoying but the purpose is not to detect this issues on free, but rather on any utilization of an object. Sometimes detecting this upon free is too far away from the action...

**Comment by chergert** [comment]
I'm still unconvinced. I've seen this done and it almost always gets removed because it adds complexity for virtually zero win. Turning up gcc warnings catches way more errors than this will.

I've been working on ideas for a new libbson API that can be made ABI stable here https://github.com/chergert/mongo-c-driver/tree/abi-stablize/bson

**Comment by jsbattig** [comment]
You are correct, overtime this type of checks represent diminishing returns, but in my case has helped me understand some idiosyncrasies of objects life cycles and some bugs in the driver that otherwise would have been very painful to find... maybe it's the point where I can remove the ZOMBIE detection code...

**Comment by jsbattig** [comment]
I will re-code this pull request without the memory protection/zombie check schema. Please drop this one, I will re-submit later.

**Comment by chergert** [comment]
Of course everyone has their preference, but for me, valgrind catches most bugs that the compiler doesn't. Especially with reading off alignment, and after free, etc. I would guess that most of the issues would be caught there.

**Comment by jsbattig** [comment]
Re-submitted pull request. Drop this one please.

**Pull request closed without merging**
