### PR TITLE
Added --prefix option for dynamic prefix when installing

### PR DESCRIPTION
**Pull request by reflection**
Also removed version from soname since install just copies libmongoc.so and libbson.so over.

### CODE REVIEW

**Comment by gjmurakami-10gen** [comment]
CDRIVER-163 - add installation prefix for scons
Started to manually merge this, and found that this is no longer a simple merge.
If you want this sooner, you can retry, otherwise this will probably be pushed back due to lower priority than other issues.

See also https://github.com/mongodb/mongo-c-driver/pull/40

**Comment by reflection** [comment]
Thanks for reviewing this.  Since my pull request, there is a new build option that works fine for us:
--install-{library,include}-path

**Comment by gjmurakami-10gen** [comment]
Thanks for your feedback and we hope that you are enjoying mongodb.

**Comment by gjmurakami-10gen** [comment]
Thanks for your input and response.  We hope that the C driver is working
well for you, and we are actively making improvements to it.

Blessings,

-Gary

On Mon, Jul 30, 2012 at 5:02 PM, reflection <
reply@reply.github.com

**Pull request closed without merging**
