### PR TITLE
Null bson

### PR DESCRIPTION
**Pull request by jeromelebel**
The goal is to make sure all bson are null (and correctly null, in some part of the code, we can see bson b = { 0, NULL }, which is not enough).
Once we are sure all bson are correctly at the beginning, I will try to make sure we destroy them correctly.

For example no data is allocated when calling bson_empty(&b), bson_init_data(&b, mydata). This is a problem because we don't know when to call bson_destroy or not...

### CODE REVIEW

**Comment by jeromelebel** [comment]
I don't know if you don't like this request or if you need something less to merge it. If so, please, close this pull request if you don't like my way to solve this the problem, or tell me what I should modify. I wish to do the same with all structures. Then after I will be able to fix all dealloc to be sure we have no memory leaks and no memory smashers on free.

Thanks,

**Comment by gjmurakami-10gen** [comment]
Jerome,

Thanks for all of you interest and work on the C driver.  We have a new
engineer, Christian Hergert, that just came on board.  There has already
been some discussion on some of the pull requests, and we hope to get back
to you with more definitive responses soon.

In general, please consider submitting smaller multiple pull requests.  For
example, if the the 64-bit type fixes were separated out into its own pull
request, then it is likely that it would be merged immediately, allowing us
to converge more quickly and focus in on the changes that require a bit
more consideration and/or discussion.

Thanks.

On Fri, Mar 15, 2013 at 6:35 AM, Jérôme Lebel notifications@github.comwrote:

> I don't know if you don't like this request or if you need something less
> to merge it. If so, please, close this pull request if you don't like my
> way to solve this the problem, or tell me what I should modify. I wish to
> do the same with all structures. Then after I will be able to fix all
> dealloc to be sure we have no memory leaks and no memory smashers on free.
> 
> Thanks,
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mongodb/mongo-c-driver/pull/72#issuecomment-14953905
> .

## 

_{_ name     : "_Gary J. Murakami, Ph.D._",
  title    : "Lead Engineer and Ruby Evangelist",
  company  : "10gen (the MongoDB company)",
  location : "New York, NY",
  email    : "gary.murakami@10gen.com",
  mobile   : "1-908-787-6621",
  im       : "gjmurakami (AIM)",
  twitter  : "@GaryMurakami",
  blog     : "grayghostwriter.blogspot.com",
  website  : "www.nobell.org",
  linkedin : "www.linkedin.com/pub/gary-murakami/1/36a/327" _}_

**Comment by jeromelebel** [comment]
Thanks, so I will wait :-)

But I did the smallest pull request possible. This is only putting NULL to a bson (nothing about other types, and nothing about dealloc, I will do both as soon as this one is accepted).

**Comment by paulmelnikow** [comment]
Isn't this new function is trying to accomplish the same thing as bson_create(.) followed by bson_init(.)?

**Comment by jeromelebel** [comment]
bson_create() can not be called if you want to do :
bson tmp_bson;
or :
bson bson_array[5];
or :
mongo_cursor my_cursor;

**Comment by paulmelnikow** [comment]
That's correct, but you can do this:

```
bson tmp_bson;
bson_init(&tmp_bson);

bson bson_array[5];
for (int i=0; i<5; ++i) bson_init(tmp_bson+i);
```

And there's no need for bson_create in those cases, since all it does is heap-allocate the bson structure.

**Comment by paulmelnikow** [comment]
A good piece of this is that you standardized the calls to the helper functions. I factored that piece into a new pull request.

**Comment by paulmelnikow** [comment]
In terms of your comments: you can now call bson_destroy() after bson_empty(&b) – see pull request #76.

In terms of bson_init_data(), I'm not sure I understand what you mean. If the user calls that directly, they should not call bson_destroy(). Is that the confusion you're trying to avoid?

**Comment by jeromelebel** [comment]
but if we don't call bson_destroy() at the end, we have a memory leak, no?

**Comment by paulmelnikow** [comment]
The data needs to be released somewhere. If the caller retains ownership of the data, they can free it directly. If they want to transfer ownership to the bson object, they can free it with bson_destroy(). I wrote some new comments to try to clarify. Want to take a look? It's pull request #90.

**Comment by jeromelebel** [comment]
What is the life cycle of errstr in bson struct?

**Comment by jeromelebel** [comment]
So if I understand correctly, bson_destroy() should be called according on who owns the data buffer? So it means that at the end, you have to know if you should call bson_destroy() according on how the bson was created. It might be a nightmare if you create a library that returns a bson to another library.

I have the feeling that this is a hack to fix another hack : https://github.com/mongodb/mongo-c-driver/commit/fcef3c0df4d789873b30484e2e87c694c310e332

I really don't like this commit. To fix both problem, we should have a function like :
int bson_init_data( bson *b , char *data, bson_bool_t should_free_data_at_the_end );

But my point of view is before fixing dealloc, we should fix alloc. That I suggesting this pull request. If it's not accepted, that's ok. So I will do the same pull request then this one for cursor. And then I will start to work on dealloc.

And of course, because of errstr, bson_destroy() should always be called.

**Comment by gerald-lindsly** [comment]
The bson struct used to contain a member called _owned_ or some such.  I
myself was sorry to see this go.  If owned, the bson data was freed on
bson_destroy() otherwise not.

**Comment by paulmelnikow** [comment]
Currently errstr is never set to anything other than NULL, nor is it touched in bson_destroy().

Sorry you don't like it that commit re bson_empty. I don't think it's perfect, but think it's an obvious improvement over the previous version, which would cause serious problems if you attempted the same. It's an incremental approach toward fixing the bigger problem, which I'm coming to understand much better as we're continuing to discussing it.

I feel strongly that `bson_create(.)` should continue to exist, that it should be a simple convenience for malloc, and equivalent to allocating a bson document on the stack. I'd support renaming create/dispose to alloc/dealloc, which seem more natural to me, and help distinguish bson_destroy and bson_dispose.

As an aside, one of the reasons I insist on consistent use of `bson_create` is that this probable and innocuous code compiles but causes terrible problems:
`bson *bson = malloc(sizeof(bson));`

I agree with restoring a parameter like free_data_on_destroy. After `owned` went away, I ended up adding a `destroyOnDealloc` flag in my library's document object. It's meant to accomplish the same thing.

If I recall correctly, there were two reasons I needed that flag: (1) I occasionally would call `bson_empty()`, which would return a data pointer to a shared buffer, and (2) I regularly call `bson_iterator_subobject(..)`, which would produce a bson document whose data buffer was a chunk inside the parent document. Of course the parent's buffer can't be freed while the child is still in use. In Objective-C, which is reference-counted, I would simply have the child own the parent. That way the parent sticks around as long as someone needs the child. In C I'm not sure what to do. Either set free_data_on_destroy to 0 for subobjects and tell the caller they also need to hold onto the parent, or else implement something more complex, like ref counting, which waits to free the parent's data buffer until any subobjects have been destroyed.

Any thoughts on which approach to take with bson documents which are subobjects?

**Comment by gerald-lindsly** [comment]
I believe there are only two cases to consider:   bson_init_data() and bson_init_size().  Either one of these should always be called to initialize a bson struct.  For bson_init_data() if we set 'owned' to false and for bson_init_size() set it to true then bson_destroy() could handle things properly. [Note that bson_init() calls bson_init_size()].  By the way, because of the lack of 'owned', in my drivers I am unnecessarily copying subobjects to the heap sometimes so that bson_destroy() doesn't flip out.  It would be nice to fix this by putting 'owned' back in the struct.

P.S.  bson_malloc() is not exactly a convenience for malloc().  bson_malloc_func() and bson_free_func() can point to alternate heap management routines.  All code internal to the driver should be written in terms of bson_malloc() and bson_free().

**Comment by paulmelnikow** [comment]
Sure, I understand what you're saying about `bson_malloc`. What I meant was this: in user code, `bson_create` is a convenience for calling `malloc` or `bson_malloc` directly.

In terms of subobjects, this is the code for `bson_iterator_subobject()`:

```
MONGO_EXPORT void bson_iterator_subobject( const bson_iterator *i, bson *sub ) {
    bson_init_data( sub, ( char * )bson_iterator_value( i ) );
    _bson_reset( sub );
    sub->finished = 1;
}
```

You're right that setting `owned` to 0 on `sub` will prevent `bson_destroy()` from flipping out when you call it on `sub`. But it won't stop the parent (with `owned = 1`)  from deallocating the buffer while you're still using `sub`.

If you have code like this:

```
bson *parent = bson_create();
bson_init_data(parent, ...); // owned = 1
bson_iterator *iter = bson_iterator_create();
bson_iterator_init(init, parent);
...
bson *subBson = bson_create();
bson_iterator_subobject(iter, subBson);
return subBson;
```

`bson_destroy(parent)` will deallocate the buffer which `subBson` still needs.

**Comment by gerald-lindsly** [comment]
I see your point.  This was an additional reason for the subobject
copying i mentioned.
 I think this ok, if we warn them that a subobject becomes invalid when
it's 'parent' is destroyed.

**Comment by paulmelnikow** [comment]
Sounds good enough to me. I'll start a branch.

**Comment by jeromelebel** [comment]
if errstr is not used, please remove it. Otherwise, make sure it is always deallocated.

**Comment by paulmelnikow** [comment]
On the mongo struct, the buffer for errstr is allocated as part of the struct. How about handling it that way here, and marking it reserved for future use?

Or do you think it should just be removed?

I had tried posting a pull request to remove errstr from the mongo object when it wasn't being used, and the pull wasn't accepted. Of course now it is being used…

**Comment by gerald-lindsly** [comment]
mogno.errstr is being used.  bson.errstr is not.  Should be safe to remove it.

**Comment by paulmelnikow** [comment]
I opened pull request #92. Please comment there!

**Comment by paulmelnikow** [comment]
I'd appreciate your comments on #93 as well.

**Comment by gjmurakami-10gen** [comment]
Closing - issue is addressed in https://github.com/mongodb/mongo-c-driver/commit/c203b7eb92169666fc87a6c69d936c98bb752bed

**Pull request closed without merging**
