### PR TITLE
Make consistent use of helper functions to create bson and cursor objects

### PR DESCRIPTION
**Pull request by paulmelnikow**
Consistently using the _create() functions helps clarify what they're for and how they should be used.

These changes came from pull request #72.

### CODE REVIEW

**Comment by gerald-lindsly** [comment]
Nice one

**Comment by paulmelnikow** [comment]
Thanks!

**Comment by gjmurakami-10gen** [comment]
Ditto - thanks!

**Comment by paulmelnikow** [comment]
Sure think. Thank you!

**Pull request merged**
