### PR TITLE
Add mongo_write_concern_create and mongo_write_concern_dispose, consistent with pattern for other types

### PR DESCRIPTION
**Pull request by paulmelnikow**

### CODE REVIEW

**Comment by paulmelnikow** [comment]
Any chance of getting this pulled in? I'd like it included for a release of [ObjCMongoDB](https://github.com/noa--/ObjCMongoDB), which I've been building against my fork in the meantime.

**Comment by gerald-lindsly** [comment]
These functions will also be needed when I upgrade my drivers to allow specification of the write concern.

**Comment by gjmurakami-10gen** [comment]
Gerald, thanks for your input, this decides it for me as I was looking for
input other than just myself.

On Sun, Mar 17, 2013 at 4:08 AM, Gerald Lindsly notifications@github.comwrote:

> These functions will also be needed when I upgrade my drivers to allow
> specification of the write concern.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mongodb/mongo-c-driver/pull/77#issuecomment-15019030
> .

## 

_{_ name     : "_Gary J. Murakami, Ph.D._",
  title    : "Lead Engineer and Ruby Evangelist",
  company  : "10gen (the MongoDB company)",
  location : "New York, NY",
  email    : "gary.murakami@10gen.com",
  mobile   : "1-908-787-6621",
  im       : "gjmurakami (AIM)",
  twitter  : "@GaryMurakami",
  blog     : "grayghostwriter.blogspot.com",
  website  : "www.nobell.org",
  linkedin : "www.linkedin.com/pub/gary-murakami/1/36a/327" _}_

**Comment by paulmelnikow** [comment]
Thanks!

**Pull request merged**
