### PR TITLE
[CDRIVER-281] gridfs: loss of the optional field `metadata`

### PR DESCRIPTION
**Pull request by yorkie**
A little lines of code to support the optional field `metadata`.
^.^

### CODE REVIEW

**Comment by yorkie** [comment]
I have created [CDRIVER-281](https://jira.mongodb.org/browse/CDRIVER-281) for this PR, sorry about before.

**Comment by yorkie** [comment]
why closing [CDRIVER-281](https://jira.mongodb.org/browse/CDRIVER-281)?

**Comment by amidvidy** [comment]
Hi yorkie, as of now we have decided to make no further changes to the legacy-c-driver. I suggest migrating to the new c driver at https://github.com/mongodb/mongo-c-driver, which supports the `metadata` field.

**Comment by yorkie** [comment]
okay i understand, thanks :)

**Comment by amidvidy** [comment]
thanks again for contributing!

**Comment by jsbattig** [comment]
@amidvidy , please take a look at this pull I closed a while ago: https://github.com/mongodb/mongo-c-driver-legacy/pull/135/files
not sure if this functionality is considered in GridFS in the new driver.
I did a lot of the refactorings of the old driver GridFS to enable stream-like operations, and I added later "filtering" capabilities that allow for compression and encryption on the fly. Unfortunately, those changes never made it to the codebase.

**Comment by amidvidy** [comment]
Hey @jsbattig, as I stated above, I don't think we are going to be adding any new functionality to the legacy-c-driver. Your patch looks pretty interesting! However, in general we would prefer someone to use an encrypted filesystem + SSL rather than implement encryption at the driver level. 

Furthermore it seems like you have some issues in your AES implementation from my cursory reading of your code. MD5 is too quick to be used as a key stretching function, you should be using something like PBKDF2 or preferably a memory-hard hash function like scrypt. Additionally you use AES in CBC mode without using a MAC which makes your scheme trivially vulnerable to ciphertext tampering. I suggest using an authenticated encryption mode like AES-GCM or AES-EAX in the future. 

Thanks again for contributing to MongoDB, though. We look forward to seeing future patches from you!

**Comment by jsbattig** [comment]
Adam, thanks for your reply!

I appreciate your recommendations on the appropriate way to implement the
encryption layer. I knew the CBC is the bare minimum for block encryption,
but I was unaware it was so susceptible to tampering. I did some research
on the algorithms you suggest and it's something I will probably
incorporate in our fork in the future and in other encryption uses on our
software.
Anyway, the point of the pull request was really to add the capability of
"filtering" streams on-line. The AES encryption capability I committed
really serves more as an example of how it's possible to use such filtering
capability.

Best regards

Sebastian

**Pull request closed without merging**
