### PR TITLE
BSON: Smooth out memory handling of data buffers

### PR DESCRIPTION
**Pull request by paulmelnikow**
This pull request restores an "owned" flag to the BSON object and is meant to solve ownership issues around the BSON data block discussed at pull request #72, specifically that calls to bson_init_data( ), bson_iterator_subobject( ), and bson_empty( ) do not allocate any memory. Those BSON objects can't be passed to bson_destroy( ) without attempting to free memory that shouldn't be freed. Programmers using the driver have been forced to keep track of whether or not they ought to call bson_destroy on a given BSON object.

There are "review" comments in bson_print_raw( ) where the driver itself had encountered this problem.

Programmers who need persistent objects also have manually needed to copy the buffer to the heap. This pull request also makes that automatic.

BSON object changes:
-  Add flag `ownsData` to BSON object which controls whether `bson_destroy`
  deallocates the data block and whether `bson_ensure_space` may reallocate
  it
-  Add error flag `BSON_DOES_NOT_OWN_DATA`, set when
  `bson_ensure_space( )` would need to expand an unowned data block

API changes:
-  Rename `bson_init_data` to `bson_init_unfinished_data`
  (will anyone even want to use this?) and add parameters for the size
  and ownership of the block
-  Add parameter to `bson_init_finished_data` for the ownership of the block
-  Add `bson_init_finished_data_with_copy( )` to more easily create
  subobjects which can outlive their parents
-  Rename iterator functions which initialize bson objects and add
  a parameter to enable copying subobject data to the heap:
  `bson_iterator_code_scope( )` is now `bson_iterator_code_scope_init( )`
  and 
  `bson_iterator_subobject( )` is now `bson_iterator_subobject_init( )`.
  Fix up these functions to either copy the blocks or return BSON objects
  with unowned blocks. Same for `gridfile_get_metadata( )`.

Minor changes:
-  Return status code instead of void from all init functions (since
  `bson_malloc` can return 0)
-  Replace `_bson_reset` with `_bson_zero`, and call it from all init functions
-  Factor `_bson_init_size` into `bson_init_size`
-  Remove `bson_shared_empty_data` check in `bson_destroy`
-  Add helper function `bson_finished_data_size( )` to get the size of a
  finalized BSON data block, and use it where applicable
-  Rewrite `bson_empty( )` and `bson_copy( )`

### CODE REVIEW

**Comment by gjmurakami-10gen** [comment]
I think that this solves a number of issues and significantly improves programmer friendliness.  I solicit other reviewers as the change while straightforward, is non-trivial.

**Comment by gerald-lindsly** [comment]
As you say, Gary.  I like it too.

**Comment by gjmurakami-10gen** [comment]
OK, I'm merging this one, please give it a run.

**Comment by gjmurakami-10gen** [comment]
Paul, looks like this can't be merged automatically.  I'll look at the other PRs and come back to it.

**Comment by paulmelnikow** [comment]
What do you think about leaving behind a deprecated API for the simpler changes, to let developers update their code over time? On the one hand the readme says it's alpha, but on the other hand there are already some other deprecated functions.

I want to make one other change, too.

Re the merge issue, I think it was removing errstr. I can try to fix it with a merge on this branch.

**Comment by gjmurakami-10gen** [comment]
Paul, you're quick!  It's merged, thanks for your work!

On Wed, Mar 20, 2013 at 4:20 PM, Paul Melnikow notifications@github.comwrote:

> What do you think about leaving behind a deprecated API for the simpler
> changes, to let developers update their code over time? On the one hand the
> readme says it's alpha, but on the other hand there are already some other
> deprecated functions.
> 
> I want to make one other change, too.
> 
> Re the merge issue, I think it was removing errstr. I can try to fix it
> with a merge on this branch.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mongodb/mongo-c-driver/pull/93#issuecomment-15200870
> .

## 

_{_ name     : "_Gary J. Murakami, Ph.D._",
  title    : "Lead Engineer and Ruby Evangelist",
  company  : "10gen (the MongoDB company)",
  location : "New York, NY",
  email    : "gary.murakami@10gen.com",
  mobile   : "1-908-787-6621",
  im       : "gjmurakami (AIM)",
  twitter  : "@GaryMurakami",
  blog     : "grayghostwriter.blogspot.com",
  website  : "www.nobell.org",
  linkedin : "www.linkedin.com/pub/gary-murakami/1/36a/327" _}_

**Comment by paulmelnikow** [comment]
Thanks, it's my pleasure! I'll post a separate PR with the other change I wanted to make (re bson_empty).

What do you think about adding a deprecated API for some of these changes?

**Comment by gerald-lindsly** [comment]
From my perspective, I'd rather not see extra clutter.  These are relatively simple function name changes or minor parametric differences.

**Pull request merged**
