### PR TITLE
Fix bson_oid_generated_time for systems with a 64bit time_t.

### PR DESCRIPTION
**Pull request by davidcrawford**
See https://jira.mongodb.org/browse/CDRIVER-195

Not sure how to write a test for this, since the failure is OS-dependent.  Would appreciate feedback on that.

### CODE REVIEW

**Comment by paulmelnikow** [comment]
Thanks for this patch.

Why use an `int` instead of simply `time_t out = 0`? I've tested that on my 64-bit system, and it seems to work correctly.

**Comment by davidcrawford** [comment]
Not all 64-bit systems have a 64-bit time_t.  The standard for time_t doesn't specify how wide it is.  In ubuntu 12.04 (I believe that's what I was using), it's 64 bits, but on my 64-bit mac it's only 32.

`bson_big_endian32` is defined as:

``` c
#define bson_big_endian32(out, in) ( memcpy(out, in, 4) )
```

So if you give it a 64 bit variable, it copies `in` into the _high_-order 4 bytes.  This change gives it a 32-bit variable as it's expecting, then lets C properly coerce it into the proper width for time_t.

**Comment by paulmelnikow** [comment]
That's strange; my 64-bit Mac seems to have a 64-bit time_t. Could it be compiler-dependent?

I see what you're saying about bson_big_endian32.

I just wrote a test case #137 which passes on my system, but from what you're saying, it should fail on yours. Want to give it a try and see?

The output on my system is `sizeof(time_t) is 8`.

**Comment by davidcrawford** [comment]
Fails on Ubuntu 12.04.2 LTS.

```
./test_bson
        d : 1    3.140000
        s : 2    hello
        s_n : 2          goodbye
        o : 3    
                a : 4    
                        0 : 5    BSON_BINDATA


        u : 6    BSON_UNDEFINED
        oid : 7          010203040506070809101112
        b : 8    true
        date : 9         72623859790382856
        n : 10   BSON_NULL
        r : 11   BSON_REGEX: ^asdf
        c : 13   BSON_CODE: function(){}
        c_n : 13         BSON_CODE: function(){}
        symbol : 14      SYMBOL: symbol
        symbol_n : 14    SYMBOL: symbol
        cws : 15         BSON_CODE_W_SCOPE: function(){return i}
         SCOPE:         i : 16   123

        timestamp : 17   i: 1, t: 2
        l : 18   1234605616436508552

sizeof(time_t) is 8


Failed ASSERT [test/bson_test.c] (343):
     bson_oid_generated_time(&oid) < cur_time + 1

./test_bson failed!
make: *** [test] Error 1
```

```
ubuntu:~/mongo-c-driver$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=12.04
DISTRIB_CODENAME=precise
DISTRIB_DESCRIPTION="Ubuntu 12.04.2 LTS"
```

**Comment by paulmelnikow** [comment]
Hey, that's good. Does it fail with `time_t out = 0`? And pass with `int out = 0`?

**Comment by davidcrawford** [comment]
It works with both `time_t out = 0` and with `int out`.  Looks like I forgot which order the bytes go in.  So `time_t out = 0` is probably a little more sensible.

**Comment by paulmelnikow** [comment]
Sounds good to me. If you update your pull request hopefully Gary will merge these in together.

**Comment by davidcrawford** [comment]
Updated.  Thanks for the help.

**Comment by paulmelnikow** [comment]
Thanks Gary. Just a reminder, there's [a bug in Jira](https://jira.mongodb.org/browse/CDRIVER-195) for this.

**Comment by gjmurakami-10gen** [comment]
Thanks to all.

On Tue, May 21, 2013 at 6:02 PM, Paul Melnikow notifications@github.comwrote:

> Thanks Gary. Just a reminder, there's a bug in Jirahttps://jira.mongodb.org/browse/CDRIVER-195for this.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mongodb/mongo-c-driver/pull/70#issuecomment-18244825
> .

## 

_{_ name     : "_Gary J. Murakami, Ph.D._",
  title    : "Lead Engineer and Ruby Evangelist",
  company  : "10gen (the MongoDB company)",
  location : "New York, NY",
  email    : "gary.murakami@10gen.com",
  mobile   : "1-908-787-6621",
  im       : "gjmurakami (AIM)",
  twitter  : "@GaryMurakami",
  blog     : "grayghostwriter.blogspot.com",
  website  : "www.nobell.org",
  linkedin : "www.linkedin.com/pub/gary-murakami/1/36a/327" _}_

**Comment by davidcrawford** [comment]
Glad I can finally wear my MongoDB committer t-shirt!

**Pull request merged**
