### PR TITLE
can set the index name

### PR DESCRIPTION
**Pull request by jeromelebel**

### CODE REVIEW

**Comment by jeromelebel** [comment]
At the same time the mongo server let us choose the index name. And it can be useful when I have too many keys to index. Close this issue if you don't want it (I'm fine with it), or if you prefer that I fix the default name.

**Comment by gjmurakami-10gen** [comment]
Jerome, I talked it over with Tyler, and we took another look at the Mongo shell and the Ruby driver.  It turns out that you can specify the name option in both of them, so adding the name option is appropriate.  And if we don't specify the name option, the server auto generates the name following the convention, so the code can be quite simple.  I did the code for this, but the gridfs test failed, and I'm still debugging.

**Comment by gjmurakami-10gen** [comment]
Aha, looks like the mongo shell generates the name, and I'm guessing that a deeper look at the Ruby driver will reveal the same.

**Comment by gjmurakami-10gen** [comment]
Jerome, I think that I have completed this in commit https://github.com/mongodb/mongo-c-driver/commit/a3e00d82a894196e96d0326527cbe2c82520cbef so please check it out.  Closing.

**Comment by jeromelebel** [comment]
it's perfect for me!

**Pull request closed without merging**
