### PR TITLE
adding support for minkey and maxkey

### PR DESCRIPTION
**Pull request by jeromelebel**
Adding support for minkey and maxkey

### CODE REVIEW

**Comment by paulmelnikow** [comment]
I see minkey and maxkey in the BSON spec but I don't understand what they're for. Could one of you explain it?

**Comment by jeromelebel** [comment]
Sorry, I have no clue what they are for... I just know some mongohub-mac users wanted that.

**Comment by gjmurakami-10gen** [comment]
http://docs.mongodb.org/manual/reference/operator/type/

MinKey and MaxKey compare less than and greater than all other possible BSON element values, respectively, and exist primarily for internal use.

I most commonly see them in the configdb for sharding, used at the extremes of shard key ranges.

**Comment by paulmelnikow** [comment]
Thanks!

**Pull request merged**
